Assignments
sureshHARDIYA/idpt pull request #21
Opened 2020-10-10 17:11 UTC by sureshHARDIYA

2020-10-10 17:19 UTC, hunghkit commented on backend/src/api/assignments/queries/assignmentsList.js
> +      permissions.casedRead,
are you sure `casedRead` permission?

2020-10-10 17:27 UTC, hunghkit commented on backend/src/api/assignments/types/assignmentEnum.js
> +  enum questionEnum {
Graphql enum, type is capitalize 
```
questionEnum -> QuestionEnum
```

2020-10-10 17:27 UTC, hunghkit commented on frontend/src/modules/assignments/assignmentsSelectors.js
> +      Permissions.values.audioRead,
audio permission?

2020-10-10 17:27 UTC, hunghkit commented on frontend/src/modules/assignments/destroy/assignmentsDestroyReducers.js
> +  if (type === actions.DESTROY_ALL_STARTED) {
you can use switch/case in here

2020-10-10 17:27 UTC, hunghkit commented on frontend/src/modules/assignments/form/assignmentsFormReducers.js
> +  if (type === actions.RESET) {
pls move to switch/case

2020-10-10 17:27 UTC, hunghkit commented on frontend/src/view/assignments/form/builder/FormBuilder/builder.js
> +  return (
can reduce "return"

2020-10-10 17:46 UTC, hunghkit commented on frontend/src/view/assignments/form/builder/FormBuilder/builder.js
> +
`initialValue` should be `record` not `formStructure `

2020-10-10 17:51 UTC, hunghkit requested changes

2020-10-10 17:51 UTC, hunghkit commented on frontend/src/view/assignments/form/builder/FormBuilder/builder.js
> +          dispatch(actions.doCreate(formData));
Alway call doCreate, so you can't edit

2020-10-11 15:57 UTC, sureshHARDIYA commented on frontend/src/view/assignments/form/builder/FormBuilder/builder.js
> +  return (
What do you mean by this?

2020-10-12 10:07 UTC, hunghkit approved these changes

2020-10-12 10:08 UTC, merged